config/routes.rb
Newsfeed::Application.routes.draw do

  resources :news_items, path: 'feed'

  get "welcome/index"
  get "omniauth_callbacks/vkontakte"
  devise_for :users,  path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'register' }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'welcome#index'

  #get '/feed', to: 'news_items#index'
  get '/profile', :to => "users#profile", :as => :profile

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  validates_presence_of :title, :text

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable, :omniauthable

  validates_presence_of :username

  has_many :news_items

  def self.find_for_vkontakte_oauth access_token
    if user = User.where(url: access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(provider: access_token.provider, 
                   url:  		 access_token.info.urls.Vkontakte, 
                   username: access_token.info.name,  
                   email: 	 access_token.uid+'@vk.com', 
                   password: Devise.friendly_token[0,20]) 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :about, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :about, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController

  before_filter :authenticate_user!
  
  def index
    @news_items = NewsItem.all
  end

  def show
    @news_item = NewsItem.find(params[:id])
  end

  # GET /news_items/1/edit
  def edit
    @news_item = NewsItem.find(params[:id])
  end

  def new
    @news_item = NewsItem.new
  end

  # POST /news_items
  # POST /news_items.json
  def create
  	@news_item = NewsItem.new(news_item_params)
    @news_item.user_id = current_user.id

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to @news_item, notice: 'News item was successfully created.' }
        format.json { render json: @news_item, status: :created, location: @news_item }
      else
        format.html { render action: "new" }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news_items/1
  # PUT /news_items/1.json
  def update
    @news_item = NewsItem.find(params[:id])

    respond_to do |format|
      if @news_item.update_attributes(news_item_params)
        format.html { redirect_to @news_item, notice: 'News item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.json
  def destroy
    @news_item = NewsItem.find(params[:id])
    @news_item.destroy

    respond_to do |format|
      format.html { redirect_to news_items_url }
      format.json { head :no_content }
    end
  end


  private

  def news_item_params
    params.require(:news_item).permit(:title, :text)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def vkontakte
    @user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Vkontakte"
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def profile
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to news_items_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper

  def date_format(news_date)
    date_diff = ((DateTime.now - news_date.to_datetime).to_i/1.day)
    case date_diff 
      when 1
        s = "Yesterday, "
      when 0
        s = "Today, "
      else
        s = news_date.strftime('%d.%m') + ' ,'    
    end 
    s + news_date.strftime('%H:%M')
  end
  
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_metrika.html.erb
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=25100318&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/25100318/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:25100318,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter25100318 = new Ya.Metrika({id:25100318,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/25100318" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsfeed</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row clearfix">
    <div class="col-md-12 column">

      <!--top-->
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="/">Новости</a>

            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to current_user.username, profile_path %></li>
                <li><%= link_to 'Создать новость', new_news_item_path %></li>
              <% else %>
                <li><%= link_to 'Войти', new_user_session_path %></li>
              <% end %>
            </ul>

          </div>
        </div>
      </div>

      <!--body-->
      <div class="container">
        <%= yield %>
      </div>

      <!--bottom-->
      <div class="navbar navbar-fixed-bottom">
        <div class="navbar-inner">
          <%= render partial: 'layouts/metrika' %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/news_items/_form.html.erb
<%= form_for(@news_item) do |f| %>
  <% if @news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

      <ul>
      <% @news_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, size: '10x10', :class => 'text_area' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                news_items_path, :class => 'btn' %>
 
<% end %>

app/views/news_items/edit.html.erb
<h1>Редактировать новость</h1>

<%= render 'form' %>

<%= link_to 'Назад', @news_item %>

app/views/news_items/index.html.erb
<div>
  <% if @news_items.length > 0 %> 
    <div class='news'>
      <div class='row'>
        <div class="span8">
          <h3>Свежая новость</h3>
          <small><%= date_format(@news_items.last.created_at) %></small><br>
           <h4><%= link_to @news_items.last.title, news_item_path(@news_items.last.id) %></h4>
          <%= @news_items.last.text %> 
        </div>
        <div class="span4">
          <h3>Другие новости</h3>
          <% @news_items[0..-2].each do |news_item| %>
            <ul class="unstyled"
              <li><%= link_to news_item.title, news_item_path(news_item.id) %></li>
            </ul>
          <% end %>
        </div>
      </div>
    
    </div>
  <% else %>
    <h3>Пока новостей нет</h3>
  <% end %>
<div>

app/views/news_items/new.html.erb
<h1>Создать новость</h1>

<%= render 'form' %>

<%= link_to 'Назад', news_items_path %>

app/views/news_items/show.html.erb
<div class='news'>
  <div class='row'>
    <div class="span2">
      <time><%= date_format(@news_item.created_at) %></time>
    </div>
    <div class="span6">
      <h4><%= @news_item.title %></h4>
    </div>
  </div>
  <div class="container">
    <%= @news_item.text %>   
  </div>      
</div>

<%= link_to('Редактировать', edit_news_item_path(@news_item.id)) + ' | '  if @news_item.user_id == current_user.id %> 
<%= link_to('Удалить', @news_item, data: { confirm: "Вы уверены?" }, method: :delete) + ' | '  if @news_item.user_id == current_user.id %>
<%= link_to 'Назад', news_items_path %>

app/views/users/profile.html.erb
<div>
  <h3>Профиль</h3>

  <p>Имя: <%= @user.username %></p>
  <p>О себе: 
    <% if @user.about.blank? %>
      <%= link_to 'Страница в VK', @user.url, target: '_blank' if @user.url %>
    <% else %>
      <%= @user.about %>
    <% end %>
  </p>
  <p>Зарегистрирован: <%= @user.created_at.strftime('%d/%m/%Y') %></p>
  <p>Последний раз заходил: <%= @user.last_sign_in_at.strftime('%d/%m/%Y') %> в <%= @user.last_sign_in_at.strftime('%H:%M:%S') %></p>

  <% if current_user == @user %>
    <p>
    <p><%= link_to 'Редактировать',edit_user_registration_path, class: 'btn btn-primary btn-small' %></p>
    <p><%= link_to 'Выйти', destroy_user_session_path, class: 'btn btn-danger btn-small', method: 'delete' %></p>
    </p>
  <% end %> 
<div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h2>Лента новостей</h2>

  <p>-здесь должен быть текст приветствия-</p>
  <p>
    <%= link_to 'Войти', new_user_session_path, class: 'btn btn-primary'%>
    <%= link_to 'Войти через VK', user_omniauth_authorize_path(:vkontakte), class: 'btn btn-primary'%>
  </p>
</div>